// <auto-generated />
namespace AdScoreShow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Copy_DurationFieldNullableInAdvertisementModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Copy_DurationFieldNullableInAdvertisementModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202001231725014_Copy_DurationFieldNullableInAdvertisementModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
